[package]
name = "network-manager"
version = "0.1.0"
license = "GPL-3.0-or-later"
authors = ["Pierre Krieger <pierre.krieger1708@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
fnv = { git = "https://github.com/dflemstr/rust-fnv", default-features = false }    # TODO: https://github.com/servo/rust-fnv/pull/22
futures = "0.3"
hashbrown = { version = "0.6.3", default-features = false }
parity-scale-codec = "1.0.5"
redshirt-interface-interface = { path = "../../interfaces/interface" }
redshirt-log-interface = { path = "../../interfaces/log" } # TODO: remove
redshirt-network-interface = { path = "../../interfaces/network" }
redshirt-syscalls = { path = "../../interfaces/syscalls" }
redshirt-tcp-interface = { path = "../../interfaces/tcp" }
redshirt-time-interface = { path = "../../interfaces/time" }
smoltcp = { git = "https://github.com/m-labs/smoltcp", default-features = false, features = ["ethernet", "proto-ipv4", "proto-ipv6", "socket-udp", "socket-tcp", "std"] }
# TODO:
#smoltcp = { version = "0.5.0", default-features = false, features = ["proto-ipv4", "proto-ipv6", "socket-udp", "socket-tcp", "std"] }
thiserror = "1.0.9"
